### PR TITLE
Now nodes send FIN message before closing connection

### PR DESCRIPTION
**Pull request by tsujio**
Address #8.

When sending request by sender and closing connection by receiver conflict, the request cannot reach the receiver and eventually times out.

Now nodes send FIN message before closing a connection and if receives FIN a node stops to use the connection.

### CODE REVIEW

**Comment by jure** [comment]
I wonder if that's related to increasing CPU usage as the uptime of the client grows. I've recently started logging PeerJS's exceptions when sending, and they increase rapidly as uptime grows:

```
// Returns true if the send succeeds.
DataConnection.prototype._trySend = function(msg) {
  try {
    this._dc.send(msg);
  } catch (e) {
    console.log(e);
    this._buffering = true;

    var self = this;
    setTimeout(function() {
      // Try again.
      self._buffering = false;
      self._tryBuffer();
    }, 100);
    return false;
  }
  return true;
}
```

The `e` here is this exception:

```
DOMException {message: "Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'", name: "InvalidStateError", code: 11, stack: "Error: Failed to execute 'send' on 'RTCDataChannel…glav/src/scholarninja/peerjs-test/peer.js:2027:12", INDEX_SIZE_ERR: 1…}
```

I'll try this out as soon as possible (in about 4 hours)

**Comment by tsujio** [comment]
PeerJS seems not to sync DataConnection.open and RTCDataChannel.readyState.
I'll investigate it.

**Comment by jure** [comment]
I'm trying this on a node in an existing network of old versions and I'm getting this:

```
Joining txg84tqtyv6lxr00 background.js:205
Error {stack: (...), message: "Invalid argument."} webrtc-chord.js:1426
Error {stack: (...), message: "Invalid argument."}
message: "Invalid argument."
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: d
data
Object {method: "INSERT_REPLICAS", params: Object, requestId: "edc446850b4a00113d6fba4a304a4fada8d4114333de02da5687c9829a85d05c", timestamp: 1404232706635}
```

I guess this is to be expected with the new FIN messages and all nodes have to update to the new webrtc-chord version?

**Comment by tsujio** [comment]
Yes, I've not considered about compatibility but it's very important.
I'm implementing #9 and it will not also have compatibility.

I'll add version to the project and message if possible.

**Comment by jure** [comment]
Semantic versioning would be appropriate and relatively easy to follow, given that this is basically an API to a Chord network. Don't know if you're familiar with it, but the summary is:

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```

http://semver.org/

With regards to this issue, I'll have to wait for everyone to update to the new version, although I think the timeouts are still present. This is what I'm currently seeing (the peers listed are from the server, and I select a random bootstrap node, then eliminate it from this list if the connection fails):

```
Peer w70oedxevbvb1emi background.js:197
Peer bphafblbh7fzuxr0 background.js:197
Peer azb6b5n53c5l8fr0 background.js:197
Peer bk94fg5dc7eqaor0 background.js:197
Peer le95m1nreyduz0k9 background.js:197
Peer d6uc47e2aigm0a4i background.js:197
Peer xvr8uko7vugi7ldi background.js:197
Peer 32jffnkshwhzolxr background.js:197
Peer nddqvjccnvkro1or background.js:197
Peer q3nyppi4u29ms4i0 background.js:197
Peer 8w7i4piyi2fkcsor background.js:197
Peer y9xp7afvx1l6usor background.js:197
Peer in5lta5hs93vj9k9 background.js:197
Peer gbju3a4jd9774x6r background.js:197
Joining bphafblbh7fzuxr0 background.js:205
Failed: Error: FIND_SUCCESSOR request to bphafblbh7fzuxr0 timed out. background.js:179
Peer w70oedxevbvb1emi background.js:197
Peer azb6b5n53c5l8fr0 background.js:197
Peer bk94fg5dc7eqaor0 background.js:197
Peer le95m1nreyduz0k9 background.js:197
Peer d6uc47e2aigm0a4i background.js:197
Peer xvr8uko7vugi7ldi background.js:197
Peer 32jffnkshwhzolxr background.js:197
Peer nddqvjccnvkro1or background.js:197
Peer q3nyppi4u29ms4i0 background.js:197
Peer y9xp7afvx1l6usor background.js:197
Peer in5lta5hs93vj9k9 background.js:197
Peer gbju3a4jd9774x6r background.js:197
Joining q3nyppi4u29ms4i0 background.js:205
Failed: Error: FIND_SUCCESSOR request to q3nyppi4u29ms4i0 timed out. background.js:179
Peer w70oedxevbvb1emi background.js:197
Peer azb6b5n53c5l8fr0 background.js:197
Peer bk94fg5dc7eqaor0 background.js:197
Peer le95m1nreyduz0k9 background.js:197
Peer d6uc47e2aigm0a4i background.js:197
Peer xvr8uko7vugi7ldi background.js:197
Peer 32jffnkshwhzolxr background.js:197
Peer nddqvjccnvkro1or background.js:197
Peer y9xp7afvx1l6usor background.js:197
Peer in5lta5hs93vj9k9 background.js:197
Peer gbju3a4jd9774x6r background.js:197
Joining w70oedxevbvb1emi background.js:205
Failed: Error: FIND_SUCCESSOR request to w70oedxevbvb1emi timed out. background.js:179
Peer azb6b5n53c5l8fr0 background.js:197
Peer bk94fg5dc7eqaor0 background.js:197
Peer le95m1nreyduz0k9 background.js:197
Peer d6uc47e2aigm0a4i background.js:197
Peer xvr8uko7vugi7ldi background.js:197
Peer 32jffnkshwhzolxr background.js:197
Peer nddqvjccnvkro1or background.js:197
Peer y9xp7afvx1l6usor background.js:197
Peer gbju3a4jd9774x6r background.js:197
Joining le95m1nreyduz0k9 background.js:205
Failed: Error: FIND_SUCCESSOR request to le95m1nreyduz0k9 timed out. background.js:179
Peer azb6b5n53c5l8fr0 background.js:197
Peer bk94fg5dc7eqaor0 background.js:197
Peer d6uc47e2aigm0a4i background.js:197
Peer xvr8uko7vugi7ldi background.js:197
Peer 32jffnkshwhzolxr background.js:197
Peer nddqvjccnvkro1or background.js:197
Peer y9xp7afvx1l6usor background.js:197
Peer gbju3a4jd9774x6r background.js:197
Joining d6uc47e2aigm0a4i background.js:205
Failed: Error: FIND_SUCCESSOR request to d6uc47e2aigm0a4i timed out. background.js:179
Peer azb6b5n53c5l8fr0 background.js:197
Peer bk94fg5dc7eqaor0 background.js:197
Peer xvr8uko7vugi7ldi background.js:197
Peer 32jffnkshwhzolxr background.js:197
Peer nddqvjccnvkro1or background.js:197
Peer y9xp7afvx1l6usor background.js:197
Peer gbju3a4jd9774x6r background.js:197
Joining azb6b5n53c5l8fr0 background.js:205
Failed: Error: FIND_SUCCESSOR request to azb6b5n53c5l8fr0 timed out. background.js:179
Peer bk94fg5dc7eqaor0 background.js:197
Peer xvr8uko7vugi7ldi background.js:197
Peer 32jffnkshwhzolxr background.js:197
Peer nddqvjccnvkro1or background.js:197
Peer y9xp7afvx1l6usor background.js:197
Peer gbju3a4jd9774x6r background.js:197
Joining xvr8uko7vugi7ldi background.js:205
My peer ID: iukin0gihc6561or
```

So as you see, the FIND_SUCCESSOR requests time out an awful lot and I'm again absolutely sure that these peers are responsive, because I check server-side. It's possible that not all have the new version, but then I would see errors in message processing, which I don't.

I'll dig deeper and try testing again tomorrow, when I'm absolutely sure all peers are updated.

**Comment by jure** [comment]
I am again seeing CPU usage going crazy after a while and the script being stuck at:

```
DataConnection.prototype._trySend = function(msg) {
  try {
    this._dc.send(msg);
  } catch (e) {
    this._buffering = true;

    var self = this;
    setTimeout(function() {
      // Try again.
      self._buffering = false;
      self._tryBuffer();
    }, 100);
    return false;
  }
  return true;
}
```

The timeline is dominated by calls to this function: 

image

And all of the exceptions are: "Failed to execute 'send' on 'RTCDataChannel'"

This causes my network to become unresponsive after a while, as a whole, as nodes using 100% CPU won't be able to respond to requests in a timely manner. Not quite sure why this is happening, but it looks like that requests are trying to be sent once the connection is already closed and then they're still trying to be sent indefinitely.

Apologies if this is not the relevant issue/pull request, but I think it's possible that all of them related to performance have a common issue, which is this trySend method being called indefinitely.

**Comment by jure** [comment]
I've managed to reproduce this "Failed to execute 'send' on 'RTCDataChannel'" behaviour with this script:
https://gist.github.com/jure/237391013962bf198633

All it took was that every 15 seconds, I `chord.leave()` one of the nodes, and then the fun begins:

```
DOMException {message: "Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'", name: "InvalidStateError", code: 11, stack: "Error: Failed to execute 'send' on 'RTCDataChannel…glav/src/scholarninja/peerjs-test/peer.js:2027:12", INDEX_SIZE_ERR: 1…} peer.js:2020
DOMException {message: "Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'", name: "InvalidStateError", code: 11, stack: "Error: Failed to execute 'send' on 'RTCDataChannel…glav/src/scholarninja/peerjs-test/peer.js:2027:12", INDEX_SIZE_ERR: 1…} peer.js:2020
DOMException {message: "Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'", name: "InvalidStateError", code: 11, stack: "Error: Failed to execute 'send' on 'RTCDataChannel…glav/src/scholarninja/peerjs-test/peer.js:2027:12", INDEX_SIZE_ERR: 1…} peer.js:2020
DOMException {message: "Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'", name: "InvalidStateError", code: 11, stack: "Error: Failed to execute 'send' on 'RTCDataChannel…glav/src/scholarninja/peerjs-test/peer.js:2027:12", INDEX_SIZE_ERR: 1…} peer.js:2020
DOMException {message: "Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'", name: "InvalidStateError", code: 11, stack: "Error: Failed to execute 'send' on 'RTCDataChannel…glav/src/scholarninja/peerjs-test/peer.js:2027:12", INDEX_SIZE_ERR: 1…} peer.js:2020
DOMException {message: "Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'", name: "InvalidStateError", code: 11, stack: "Error: Failed to execute 'send' on 'RTCDataChannel…glav/src/scholarninja/peerjs-test/peer.js:2027:12", INDEX_SIZE_ERR: 1…} 
```

This goes on forever and only gets worse as more nodes leave.

**Comment by jure** [comment]
I've managed to prevent this behaviour by once again checking within this trySend -> tryBuffer -> trySend loop, if the connection is open or not:

```
// Try to send the first message in the buffer.
DataConnection.prototype._tryBuffer = function() {
  if (this._buffer.length === 0) {
    return;
  }

  // Added this conditional.
  if (!this.open) {
    this.emit('error', new Error('Connection is not open.'));
    return;
  }
  // End of addition.

  var msg = this._buffer[0];

  if (this._trySend(msg)) {
    this._buffer.shift();
    this.bufferSize = this._buffer.length;
    this._tryBuffer();
  }
}
```

Right now it appears to be a PeerJS issue (cc @michelle). I'll open an issue there.

**Comment by tsujio** [comment]
I had pushed 76b730436456076f6b2eaf27585f680d235db374 and close this PR.

**Pull request closed without merging**
